"""Bundle the site's webfonts locally (no CDN dependency at runtime)."""
import re
import pathlib
import urllib.request

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "fonts"
OUT.mkdir(parents=True, exist_ok=True)

UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")

FAMILIES = {
    # display: editorial serif with real character
    "Newsreader": "https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,500;6..72,600;6..72,700&display=swap",
    # body / UI: Stanford-adjacent humanist sans
    "SourceSans3": "https://fonts.googleapis.com/css2?family=Source+Sans+3:wght@400;600;700&display=swap",
}

faces = []
for fam, url in FAMILIES.items():
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    css = urllib.request.urlopen(req, timeout=30).read().decode()
    # keep only latin subsets to stay small
    blocks = re.findall(r"/\*\s*([\w\-\[\]]+)\s*\*/\s*(@font-face\s*\{[^}]+\})", css)
    seen = 0
    for subset, block in blocks:
        if subset not in ("latin", "latin-ext"):
            continue
        m = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not m:
            continue
        weight = re.search(r"font-weight:\s*([^;]+);", block).group(1).strip()
        style = re.search(r"font-style:\s*([^;]+);", block)
        style = style.group(1).strip() if style else "normal"
        name = f"{fam}-{weight.replace(' ', '_')}-{subset}-{seen}.woff2"
        data = urllib.request.urlopen(
            urllib.request.Request(m.group(1), headers={"User-Agent": UA}), timeout=30).read()
        (OUT / name).write_bytes(data)
        family = "Newsreader" if fam == "Newsreader" else "Source Sans 3"
        rng = re.search(r"unicode-range:\s*([^;]+);", block)
        faces.append(
            f"@font-face {{\n"
            f"  font-family: '{family}';\n"
            f"  font-style: {style};\n"
            f"  font-weight: {weight};\n"
            f"  font-display: swap;\n"
            f"  src: url('fonts/{name}') format('woff2');\n"
            + (f"  unicode-range: {rng.group(1)};\n" if rng else "")
            + f"}}")
        seen += 1
        print("saved", name, len(data), "bytes")

(REPO / "fonts.css").write_text(
    "/* Bundled webfonts — generated by tmp/fetch_fonts.py, do not hand-edit. */\n\n"
    + "\n\n".join(faces) + "\n")
print("wrote fonts.css with", len(faces), "faces")
